"""Single methodology catalogue shared by API, dashboard and saved results."""

METHODS = [
    ("Data Integrity & Bias Audit", "Raw OHLCV checks and truncated-history signal invariance at temporal boundaries.", "Finite checks cannot prove absence of all leakage. PIT membership, calendars and adjustment ledgers need independent provenance.", "Raw OHLCV and a causal strategy adapter; no forward-fill repair."),
    ("Chronological Train / Validation / True OOS", "Disjoint temporal segments with common warmup and independent return metrics; prior signal/position context retained.", "Previously inspected dates remain retrospective. True OOS is N-A for archived research; future paper observations are separately recorded.", "At least two returns per segment; configured minimum for interpretation."),
    ("Walk-Forward Validation", "Rolling/expanding training context; frozen rules applied to complete disjoint forward windows. Fold metrics and dispersion.", "Rule strategies have no fitted parameters. No optimizing on test windows. Bounded folds exclude the final chronological test segment.", "Training warmup plus one complete forward window; partial windows excluded."),
    ("Parameter Stability / Sensitivity", "Recompute one-sleeve-at-a-time lookback perturbations on development data, with all candidates retained.", "Local sensitivity is exploratory and does not prove robustness. No selection on final chronological test dates.", "At least two distinct valid parameter configurations with nondegenerate results."),
    ("Transaction-Cost Stress", "Rerun the existing accounting engine at 1x/2x/3x commissions, slippage, half-spread and borrow. Bisect extra per-side bps to zero geometric return.", "Linear costs and fixed targets; break-even is model-specific. Taxes, financing, borrow recalls and nonlinear impact omitted.", "Finite prices/targets, known cost assumptions and positive turnover for break-even."),
    ("Liquidity & Execution Stress", "Next-close whole-share/cash replay; cap fills by prior trailing volume, vary delay and slippage. Estimate capital supported by planned participation.", "Long-only cash accounts only. Adjusted units and daily volume are approximate; no book, exchange calendar or empirical impact model implied.", "Positive prices, complete volume, unlevered long-only targets; 20 prior volume bars."),
    ("Bootstrap / Monte Carlo Resampling", "Seeded circular moving-block bootstrap of daily net returns; percentile Sharpe/CAGR/return/drawdown intervals.", "Stationarity and weak dependence; block length controls memory. Historical resampling cannot invent unseen tails or forecast profitability.", "Configured minimum, >=3 blocks and nonzero variance; 100–5000 replications."),
    ("Statistical Significance", "Intercept-only Newey-West HAC mean test and confidence interval; one-sided null mean <=0.", "Asymptotic normal approximation, weak stationarity and finite moments; bandwidth configurable. P-values are not profitability probabilities.", "Configured minimum, >=2*HAC lags+3 observations and positive long-run variance."),
    ("Multiple-Testing / Data-Snooping Control", "Append every attempted variant and run; Benjamini–Yekutieli FDR adjustment of valid aligned-family HAC p-values.", "BY permits dependent tests but assumes valid p-values and a disclosed family. Partial/adaptive histories and external trials remain uncorrected.", "At least two valid comparable trials; failed/unusable trials disclosed, never dropped from registry."),
    ("Deflated Sharpe Ratio & PBO", "Bailey–López de Prado DSR and exact combinatorially symmetric cross-validation (CSCV).", "DSR assumes IID returns and a documented effective independent trial count. CSCV is retrospective, assumes comparable candidate paths, and is not a chronological OOS test.", "DSR >=2 trials and nonzero cross-trial variance; CSCV even 4–12 blocks, >=2 candidates, configured minimum in each half."),
    ("Regime Survival", "Conditional returns by lagged existing regime labels, prior benchmark trend and trailing volatility; report return concentration.", "Conditional returns are noncontiguous; their compounded return is a diagnostic, not an investable regime strategy. HMM requires filtered train-only states.", "Configured minimum per state; unsupported HMM inputs return N-A."),
    ("Benchmark & Factor Attribution", "Aligned benchmark comparison and OLS factor regression with HAC coefficient/alpha intervals.", "Benchmark factor uses raw daily returns and a zero cash hurdle. Alpha is model-dependent, not proof of skill; modular factor provider may supply verified factors.", "Configured minimum, full-rank factors, >=10 observations per coefficient."),
    ("Cross-Asset / Universe Robustness", "Rerun the same strategy on deterministic leave-one-out universe subsets; retain failures and breadth.", "Tests only available constituents. No claim of universal transfer or a point-in-time universe; subset selection is disclosed.", "At least three instruments; bounded subsets leave at least two assets."),
    ("Temporal Stability / Subperiod Survival", "Calendar-year and rolling-window metrics, dispersion and absolute P&L concentration by year.", "Overlapping rolling estimates are dependent; partial years labeled. No automatic structural-break significance claim.", "Two returns for descriptive periods; configured minimum for inferential metrics."),
    ("Portfolio Interaction", "Sleeve correlations, covariance-based marginal risk and counterfactual leave-one-sleeve-out reruns; optional existing-experiment portfolio mix.", "Standalone sleeve returns do not sum to allocated portfolio. Counterfactual reruns capture allocation constraints; peer mix assumes periodic fractional rebalancing.", "At least two sleeves or aligned peer experiment returns with nonzero variance."),
    ("Tail-Risk & Scenario Stress", "Historical 95% loss VaR/ES, worst days and rolling periods, drawdown duration/recovery; frozen-exposure synthetic gap.", "Empirical tails have few observations. A simultaneous price gap is a scenario, not a probability. Fractional engine has no individual closed-trade ledger.", "Configured minimum and >=3 expected tail observations; current executed weights for gap shock."),
    ("Paper-Trading / Forward Validation", "Immutable prospectively registered signal/fill/mark events; compare realized vs expected costs, exposures and NAV.", "Local recorded paper evidence, not broker verification. Reject backdating and signals after fills. No historical bootstrap or backtest may populate the ledger.", "Frozen experiment/version at registration, subsequently timestamped paper observations; minimum returns for performance statistics."),
    ("Live Performance Monitoring", "Pure monitor interface compares realized returns, costs, exposures and regimes against a frozen expected baseline.", "Live feed/adapter unavailable; execution disabled. Monitoring calculations can be tested with explicitly labeled fixtures, never surfaced as live observations.", "Authenticated production ledger, reconciliation and broker risk services are not connected: N-A."),
]


def method(layer_id):
    name, methodology, assumptions, minimum_data = METHODS[layer_id - 1]
    return dict(id=layer_id, name=name, methodology=methodology, assumptions=assumptions, minimum_data=minimum_data)
