'use client';
import {useState} from 'react';
import {candleTimestamp,type Row} from '@/lib/flagship/evidence-results';

export function EvidenceCandles({rows,currency}:{rows:Row[];currency:string}){
  const [offset,setOffset]=useState(Math.max(0,rows.length-120)),[count,setCount]=useState(120);
  const start=Math.min(offset,Math.max(0,rows.length-count)),visible=rows.slice(start,start+count);
  if(!visible.length||!['open','high','low','close'].every(key=>typeof visible[0][key]==='number'))return null;
  const min=Math.min(...visible.map(r=>Number(r.low))),max=Math.max(...visible.map(r=>Number(r.high))),span=max-min||1;
  const volume=Math.max(1,...visible.map(r=>Number(r.volume)||0));
  const y=(price:number)=>20+220*(1-(price-min)/span),width=840/visible.length;
  return <figure className="flagship-chart"><figcaption>Price and volume · {currency} · green up, red down · UTC where source zone is known</figcaption><svg viewBox="0 0 960 350" role="img" aria-label="Historical candlesticks and volume" className="w-full"><line x1="20" x2="860" y1="245" y2="245" stroke="#333333"/>{[min,(min+max)/2,max].map((price,i)=><g key={i}><line x1="20" x2="860" y1={y(price)} y2={y(price)} stroke="#242424"/><text x="870" y={y(price)+4} fill="#a3a3a3" fontSize="13">{price.toLocaleString(undefined,{maximumFractionDigits:2})}</text></g>)}{visible.map((row,i)=>{const x=20+(i+.5)*width,color=Number(row.close)>=Number(row.open)?'#4ade80':'#f87171';return <g key={i}><title>{candleTimestamp(row.timestamp)} | O {String(row.open)} H {String(row.high)} L {String(row.low)} C {String(row.close)} | Volume {String(row.volume)}</title><line x1={x} x2={x} y1={y(Number(row.high))} y2={y(Number(row.low))} stroke={color}/><rect x={x-width*.3} y={Math.min(y(Number(row.open)),y(Number(row.close)))} width={Math.max(1,width*.6)} height={Math.max(1,Math.abs(y(Number(row.open))-y(Number(row.close))))} fill={color}/><rect x={x-width*.3} y={325-65*(Number(row.volume)||0)/volume} width={Math.max(1,width*.6)} height={65*(Number(row.volume)||0)/volume} fill={color} opacity=".65"/></g>;})}<text x="20" y="348" fill="#a3a3a3" fontSize="13">{candleTimestamp(visible[0].timestamp)}</text><text x="860" y="348" textAnchor="end" fill="#a3a3a3" fontSize="13">{candleTimestamp(visible.at(-1)?.timestamp)}</text></svg><div className="flagship-fields"><label>Visible bars ({visible.length})<input aria-label="Candlestick zoom" type="range" min="20" max="600" step="10" value={count} onChange={e=>setCount(Number(e.target.value))}/></label><label>History position ({start+1}–{start+visible.length} of {rows.length})<input aria-label="Candlestick history position" type="range" min="0" max={Math.max(0,rows.length-count)} value={start} onChange={e=>setOffset(Number(e.target.value))}/></label></div></figure>;
}
