'use client';
import {useEffect,useMemo,useRef,useState,useId} from 'react';
import {chartRows,drawdownRows,normalizedPeriods,chartAxis,useGenericEquityCharts} from '@/lib/flagship/evidence-results';
import {isPerformanceValue,performanceTone} from '@/lib/performance-colors';
import {EvidenceCandles} from './evidence-candles';
import {GuidedInputs,type InputSchema} from './evidence-inputs';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect as Select,NativeSelectOption as Option} from '@/components/ui/native-select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Brush} from 'recharts';
import {RefreshCw,Download,Play,Square} from 'lucide-react';

type RecordValue=Record<string,unknown>;
type Schema={properties:Record<string,{type?:string;title?:string;enum?:string[];minimum?:number;maximum?:number;default?:unknown}>};
type Catalog={bar:Schema;mm:Schema;bar_defaults:RecordValue;mm_defaults:RecordValue;templates:Record<string,RecordValue>;kinds:string[];mm_limitations:string[];strategy:InputSchema;hypothesis:InputSchema;calendar:unknown;quant?:Record<string,{schema:InputSchema;defaults:RecordValue}>};
type Summary={id:string;name:string;created:string};
type Artifact={id:string;kind:string;artifact:RecordValue;events:{action:string;body:RecordValue}[]};
const base='/integrations/engine/api/evidence';
async function api<T>(path:string,payload?:unknown):Promise<T>{
  const response=await fetch(base+path,{method:payload===undefined?'GET':'POST',headers:payload===undefined?undefined:{'Content-Type':'application/json'},body:payload===undefined?undefined:JSON.stringify({payload})});
  let body:RecordValue;try{body=await response.json() as RecordValue;}catch{throw new Error('Research engine unavailable. Reconnect to try again.');}
  if(!response.ok)throw new Error(typeof body.detail==='string'?body.detail:typeof body.error==='string'?body.error:JSON.stringify(body.detail)||'Research request failed');
  return body as T;
}
const title=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
function Json({value}:{value:unknown}){return <pre className="flagship-json">{JSON.stringify(value,null,2)}</pre>;}
function Fields({schema,value,change}:{schema:Schema;value:RecordValue;change:(v:RecordValue)=>void}){
  return <div className="flagship-fields">{Object.entries(schema.properties).map(([key,p])=><label key={key}>{title(key)}{p.enum?<Select value={String(value[key]??p.default??'')} onChange={e=>change({...value,[key]:e.target.value})}>{p.enum.map(v=><Option key={v}>{v}</Option>)}</Select>:<Input type={p.type==='integer'||p.type==='number'?'number':'text'} step={p.type==='integer'?1:'any'} min={p.minimum} max={p.maximum} value={String(value[key]??p.default??'')} onChange={e=>change({...value,[key]:p.type==='integer'||p.type==='number'?Number(e.target.value):e.target.value})}/>}</label>)}</div>;
}
function Grid({rows,context=""}:{rows:RecordValue[];context?:string}){
  const [page,setPage]=useState(0),columns=Array.from(new Set(rows.slice(0,50).flatMap(Object.keys)));
  if(!rows.length)return <p className="muted">No observations.</p>;
  const last=Math.max(0,Math.ceil(rows.length/50)-1),current=Math.min(page,last);
  return <div className="flagship-table"><Table><TableHeader><TableRow>{columns.map(k=><TableHead key={k}>{title(k)}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice(current*50,current*50+50).map((r,i)=><TableRow key={i}>{columns.map(k=><TableCell key={k} className={performanceTone(k,r[k],context)}>{typeof r[k]==='number'?Number(r[k]).toLocaleString(undefined,{maximumFractionDigits:6,notation:Math.abs(Number(r[k]))>0&&Math.abs(Number(r[k]))<.00001?'scientific':'standard'}):typeof r[k]==='object'?JSON.stringify(r[k]):String(r[k]??'—')}</TableCell>)}</TableRow>)}</TableBody></Table><div className="flagship-toolbar"><span>{rows.length.toLocaleString()} rows · Page {current+1} of {last+1}</span><Button variant="outline" disabled={!current} onClick={()=>setPage(current-1)}>Previous</Button><Button variant="outline" disabled={current===last} onClick={()=>setPage(current+1)}>Next</Button></div></div>;
}
function Chart({rows,keys,label,x}:{rows:RecordValue[];keys:string[];label:string;x?:string}){
  const chartId=useId().replaceAll(":", "");
  const displayed=useMemo(()=>chartRows(rows,keys),[rows,keys]);
  if(!rows.length||!keys.length)return null;
  const axis=chartAxis(rows,x);
  const numericX=Boolean(axis&&typeof rows[0]?.[axis]==='number');
  const colors=['#ededed','#a3a3a3','#737373','#d4d4d4','#525252'];
  const financial=keys.filter(k=>isPerformanceValue(k,label));
  const series=keys.map((key,i)=>{
    const values=displayed.flatMap(row=>typeof row[key]==='number'&&Number.isFinite(row[key])?[Number(row[key])]:[]);
    const min=values.length?Math.min(...values):0,max=values.length?Math.max(...values):0;
    const id=`pnl-${chartId}-${i}`;
    return {id,offset:max===min?0:max/(max-min),color:!financial.includes(key)?colors[i%colors.length]:min===0&&max===0?'#a3a3a3':min>=0?'#4ade80':max<=0?'#f87171':`url(#${id})`};
  });
  return <figure className="flagship-chart"><figcaption>{label} · {keys.map(title).join(' / ')}{displayed.length<rows.length?' · sampled with per-series extrema; full observations in tables/export':''}</figcaption><ResponsiveContainer width="100%" height={280}><LineChart data={displayed}>
    <defs>{series.filter(s=>s.color.startsWith("url")).map(s=><linearGradient key={s.id} id={s.id} x1="0" y1="0" x2="0" y2="1"><stop offset={s.offset} stopColor="#4ade80"/><stop offset={s.offset} stopColor="#f87171"/></linearGradient>)}</defs>
    <CartesianGrid stroke="#242424" vertical={false}/><XAxis dataKey={axis} type={numericX?"number":"category"} domain={numericX?["dataMin","dataMax"]:undefined} tickFormatter={numericX?v=>Number(v).toLocaleString(undefined,{maximumFractionDigits:4}):undefined} minTickGap={65} tick={{fontSize:12}}/><YAxis width={78} tick={{fontSize:12}} domain={['dataMin','dataMax']}/>
    <Tooltip contentStyle={{background:'#000',border:'1px solid #404040'}} formatter={(value,name)=><span className={performanceTone(String(name),typeof value==='number'?value:Number(value),label)}>{typeof value==='number'?value.toLocaleString(undefined,{maximumFractionDigits:6}):String(value)}</span>}/>
    {keys.map((k,i)=>{const signed=financial.includes(k);return <Line key={k} dataKey={k} stroke={series[i].color} strokeDasharray={signed&&financial.indexOf(k)>0?'5 3':undefined} dot={false} isAnimationActive={false}/>;})}<Brush height={20} stroke="#404040" fill="#000" dataKey={axis}/></LineChart></ResponsiveContainer></figure>;

}
function Result({record}:{record:Artifact}){
  const a=record.artifact;
  const [field,setField]=useState('');
  const results:Record<string,RecordValue>=a.results as Record<string,RecordValue>||{Result:(a.result||a) as RecordValue};
  const sections=Object.entries(results).flatMap(([label,r])=>Object.entries(r).filter(([,v])=>Array.isArray(v)&&v.length>0&&typeof v[0]==='object').map(([key,v])=>({key:label+' / '+key,rows:v as RecordValue[]})));
  if(Array.isArray(a.latency_sensitivity))sections.push({key:'Latency sensitivity',rows:a.latency_sensitivity as RecordValue[]});
  if(Array.isArray(a.rows))sections.push({key:'Source observations',rows:a.rows as RecordValue[]});
  const observations=(a.signal_study as RecordValue)?.observations;
  if(Array.isArray(observations))sections.push({key:'Signal research / observations',rows:observations});
  const normalized=useMemo(()=>normalizedPeriods(results),[results]);
  const selected=sections.find(s=>s.key===field)||sections[0];
  return <div className="space-y-4"><div className="flagship-toolbar"><h3>{String(a.name||record.kind)}</h3><a className="button secondary" href={`${base}/artifacts/${record.kind}/${record.id}/export`}><Download size={16}/>Export complete evidence</a></div>
    {Boolean(a.synthetic||(a.source as RecordValue)?.synthetic||(a.config as RecordValue)?.source==='synthetic')&&<p className="flagship-warning">SYNTHETIC SCENARIO · Artificial market observations. Results test assumptions and mechanics.</p>}
    {record.kind==='lab_report'&&<><Chart rows={normalized} keys={Object.keys(results)} label="Equity rebased to 100 · aligned by elapsed bar" x="elapsed_bar"/><p>Periods reset starting cash and warm-up independently. Calendar durations may differ.</p></>}
    {Object.entries(results).map(([label,r])=>{const equity=r.equity as RecordValue[]|undefined,curve=r.curve as RecordValue[]|undefined;const initial=Number((r.configuration as RecordValue)?.initial_cash||(a.configuration as RecordValue)?.initial_cash);const x=Object.keys(equity?.[0]||{}).find(k=>['date','timestamp','step'].includes(k));return <section key={label}><h3>{label}</h3>{r.metrics!=null&&<Grid rows={[r.metrics as RecordValue]}/>}{r.actual_period!=null&&<Json value={r.actual_period}/>}{equity&&useGenericEquityCharts(a,equity)&&<><Chart rows={equity} keys={['equity','gross_same_positions','buy_hold_gross'].filter(k=>k in (equity[0]||{}))} label="Portfolio value · quote units" x={x}/>{initial>0&&<Chart rows={drawdownRows(equity,initial)} keys={['drawdown_percent']} label="Drawdown · percent from running peak including starting cash" x={x}/>}</>}{curve&&<><Chart rows={curve} keys={['pnl','arb_pnl','fees']} label="P&L and fees · scenario units" x="time_ms"/><Chart rows={curve} keys={['fast_mid','slow_mid','bid_quote','ask_quote']} label="Venue prices and active quotes · scenario units" x="time_ms"/><Chart rows={curve} keys={['inventory']} label="Inventory · scenario units" x="time_ms"/></>}</section>;})}
    {Array.isArray(a.charts)&&a.charts.map((item,i)=>{const c=item as {section:string;table:string;keys:string[];x?:string;label:string};const rows=results[c.section]?.[c.table];return Array.isArray(rows)?<Chart key={i} rows={rows as RecordValue[]} keys={c.keys} label={c.label} x={c.x}/>:null;})}
    {Array.isArray(a.latency_sensitivity)&&<Chart rows={a.latency_sensitivity as RecordValue[]} keys={['net_pnl']} label="Outbound latency sensitivity · identical synthetic events" x="outbound_latency_ms"/>}
    {a.benchmark!=null&&<details><summary>Benchmark comparison</summary><Json value={a.benchmark}/></details>}{a.signal_study!=null&&<details><summary>Signal research diagnostics</summary><Json value={Object.fromEntries(Object.entries(a.signal_study as RecordValue).filter(([k])=>k!=='observations'))}/></details>}
    {Array.isArray(a.rows)&&a.rows.length>0&&<EvidenceCandles rows={a.rows as RecordValue[]} currency={String(a.currency||"quote units")}/>}
    {selected&&<><Select aria-label="Inspect result table" value={selected.key} onChange={e=>setField(e.target.value)}>{sections.map(s=><Option key={s.key}>{s.key}</Option>)}</Select><Grid key={selected.key} rows={selected.rows} context={selected.key}/>{record.kind!=='quant_result'&&record.kind!=='quant_dataset'&&<Chart rows={selected.rows} keys={Object.keys(selected.rows[0]||{}).filter(k=>typeof selected.rows[0][k]==='number'&&!/time|date/.test(k)).slice(0,4)} x={Object.keys(selected.rows[0]||{}).find(k=>/timestamp|time_ms|date|latency_ms/.test(k))} label={selected.key}/>}</>}
    {a.actual!=null&&<Json value={{actual_coverage:a.actual,currency:a.currency}}/>}{Array.isArray(a.limitations)&&<details><summary>Source and model limitations</summary>{a.limitations.map((note,i)=><p key={i}>{String(note)}</p>)}</details>}{record.kind==='regime_archive'&&<p>Original archived record. Historical absolute file references may point to shared reports overwritten by later runs. Available snapshots are included in the export; missing evidence has not been recreated.</p>}<details><summary>Source, configuration, assumptions and complete result</summary><Json value={a}/></details>
    {record.events.length>0&&<details><summary>Audit history</summary><Grid rows={record.events}/></details>}
  </div>;
}
const advanced:Record<string,{label:string;payload:RecordValue;note:string}>={
  'regime-suite':{label:'Run full regime library scenario',payload:{acknowledge:false},note:'Synthetic 900-session scenario with all 14 strategies in the retained command-line suite, generated earnings, pairs, regime analysis, benchmarks, robustness and HTML report. Fractional weight accounting; full-sample pair selection makes this a legacy in-sample diagnostic, not causal validation. No broker fills. Acknowledge before running.'},
  'save-hypothesis':{label:'Save hypothesis version',payload:{},note:'Select a formulation template below, edit the specification, then save a version. Templates are untested assumptions.'},
  guidance:{label:'Check hypothesis formulation',payload:{},note:'Check a hypothesis against the existing Evidence formulation rules.'},
  transition:{label:'Record hypothesis state',payload:{id:'',state:'specified',reason:''},note:'States: draft, specified, testing, rejected, inconclusive, candidate for forward testing.'},
  'freeze-strategy':{label:'Freeze strategy',payload:{name:'Daily research specification',version:1,hypothesis_id:'',dataset_id:'',universe:[],feature:'momentum',lookback:20,train_start:'',train_end:'',validation_start:'',validation_end:'',holdout_start:'',holdout_end:'',costs:[],acknowledge_limitations:false},note:'Use frozen hypothesis and dataset IDs. All six date boundaries, historical costs and limitation acknowledgement are required. Full schema is available below.'},
  run:{label:'Run registered daily research',payload:{strategy_id:'',partition:'validation',consume_holdout:false},note:'Partitions: training, validation, holdout. A holdout run consumes the final holdout for its family even if evaluation fails. Set consume_holdout to true only when you accept this.'},
  robustness:{label:'Run bounded robustness',payload:{strategy_id:'',variants:[],planned:false},note:'At most 25 explicit variants, validation data only. Record whether the checks were defined before viewing results.'},
  'walk-forward':{label:'Run walk-forward',payload:{strategy_id:'',lookbacks:[],train_sessions:252,validation_sessions:63,test_sessions:63},note:'Expanding training with inner validation. Final holdout excluded; each fold resets cash.'},
  review:{label:'Save forward review',payload:{report_id:'',notes:Object.fromEntries(['hypothesis_completeness','data_adequacy','chronological_correctness','out_of_sample_evidence','cost_parameter_sensitivity','concentration_capacity','portfolio_fit','reproducibility'].map(k=>[k,{outcome:'unavailable',evidence:''}]))},note:'Record evidence for all eight criteria. Review outcomes are researcher attestations.'},
  'import-csv':{label:'Import strict daily CSV',payload:{csv:'',metadata:{source:{},instruments:[],calendar:{},start:'',end:'',price_note:'',corporate_actions:[]}},note:'Choose a CSV and source manifest JSON below. Original bytes, calendar, instrument mapping and corporate actions are validated.'},
  'freeze-download':{label:'Freeze downloaded history',payload:{download_id:'',calendar:{},price_note:'',corporate_actions:[]},note:'Supply a sourced calendar with coverage bounds and exact sessions; all requested history must be present.'},
  'fetch-master':{label:'Fetch official instrument master',payload:{},note:'Downloads the official NSE instrument mapping. Current mapping does not establish historical membership.'},
  'search-master':{label:'Search instrument master',payload:{version:'',query:''},note:'Use the mapping version ID from the artifact library. Search returns validated instrument records for downloads.'},
  download:{label:'Download / resume Angel history',payload:{instruments:[],start:'',end:'',refresh:false},note:'Uses the separate historical-data session below. Repeated identical requests resume saved checkpoints; refresh explicitly re-fetches history.'},
};

export default function EvidenceWorkspace({initial='Trading lab'}:{initial?:string}){
  const [catalog,setCatalog]=useState<Catalog|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const quantNotes:Record<string,{label:string;note:string}>={
    'efficient-frontier':{label:'Construct an efficient frontier',note:'Long-only mean–variance portfolios from a frozen history. The maximum weight applies to every asset. The saved minimum-variance allocation can feed the risk simulator; returns are estimates, not realized performance.'},
    'arima-forecast':{label:'Validate ARIMA against a naive forecast',note:'Choose an asset, model order and final test window before running. Both models predict the same dates using prior observations only. Training ADF/ACF diagnostics and fit warnings are retained.'},
    'hmm-multi-strategy':{label:'Run HMM multi-strategy allocation',note:'Combine momentum, mean reversion and statistical arbitrage using filtered regime probabilities. Training refits use available history only. Compare dynamic and static budgets with whole shares, cash, collateral and costs; inspect regime attribution and convergence diagnostics.'},
    'basket-walk-forward':{label:'Optimize a cointegration basket',note:'Tune weights, lookback and entry/exit thresholds with seeded Optuna trials on inner validation windows. Compare the frozen selection with a fixed baseline on subsequent unseen dates. Each fold funds and liquidates its own account; improvement is measured, never assumed.'},
    'history-download':{label:'Load Yahoo / Massive / Synthetic multi-asset history',note:'Choose one provider for all assets. Massive supports US daily history up to two years. Synthetic uses fixed dates and seed 42. Provider errors never switch sources.'},
    'history-import':{label:'Import multi-asset price CSV',note:'CSV columns: date, then one column per asset. Use increasing UTC YYYY-MM-DD date labels and complete positive adjusted prices in a single currency. Document the source and session coverage.'},
    'history-scenario':{label:'Generate synthetic multi-asset history',note:'Artificial correlated prices with a common random walk and stationary deviations. Seeded and reproducible, for model mechanics only.'},
    'history-from-lab':{label:'Combine saved daily lab histories',note:'Provide daily lab dataset IDs and the requested date window. Every asset must have the same observed dates and currency. No missing values are filled.'},
    'multi-asset-risk':{label:'Simulate multi-asset risk and stresses',note:'Select a frozen history. Leave weights empty for equal weights, or specify every asset in JSON. An optional saved allocation must match the history and its final date. Reports 10,000+ correlated paths with volatility and correlation stresses.'},

    'options-benchmark':{label:'Benchmark Python and C++ pricing',note:'Compile the C++ model and compare price plus five Greeks on identical seeded inputs. Reports observed timings and numerical errors; first compilation may take a few minutes.'},
    'options-pricing':{label:'Price European options and Greeks',note:'Black–Scholes theoretical pricing, without dividends. Vega and rho are per 1.00 change; theta is per year. This does not retrieve market quotes.'},
    'options-simulation':{label:'Run synthetic options market making',note:'Seeded GBM and synthetic customer flow. Quotes and whole-share hedge targets become eligible at the next event. Cash, collateral and inventory limits may reject trades. The run must end before expiry; final holdings remain marked and open.'},
  };
  const actions={...advanced,...Object.fromEntries(Object.entries(catalog?.quant||{}).map(([key,item])=>[key,{...(quantNotes[key]||{label:title(key),note:''}),payload:item.defaults}]))};
  const [bar,setBar]=useState<RecordValue>({}),[mm,setMm]=useState<RecordValue>({});
  const [source,setSource]=useState('yahoo'),[symbol,setSymbol]=useState('RELIANCE.NS'),[interval,setIntervalValue]=useState('1d');
  const [start,setStart]=useState(''),[end,setEnd]=useState(''),[seed,setSeed]=useState(42),[vol,setVol]=useState(.02),[drift,setDrift]=useState(.0002);
  const [dataset,setDataset]=useState(''),[datasets,setDatasets]=useState<Summary[]>([]),[datasetOffset,setDatasetOffset]=useState(0),[datasetTotal,setDatasetTotal]=useState(0),[dates,setDates]=useState({a_start:'',a_end:'',b_start:'',b_end:''}),[ack,setAck]=useState(false),[mmAck,setMmAck]=useState(false);
  const [kind,setKind]=useState('lab_report'),[items,setItems]=useState<Summary[]>([]),[offset,setOffset]=useState(0),[total,setTotal]=useState(0),[active,setActive]=useState<Artifact|null>(null),[job,setJob]=useState<Artifact|null>(null);
  const actionDrafts=useRef<Record<string,string>>({});
  const [action,setAction]=useState('save-hypothesis'),[editor,setEditor]=useState('{}'),[totp,setTotp]=useState('');
  const [tab,setTab]=useState(initial==='Market making'?'mm':initial==='Advanced research'?'advanced':'bars');
  useEffect(()=>{if(['Trading lab','Market making','Advanced research'].includes(initial))setTab(initial==='Market making'?'mm':initial==='Advanced research'?'advanced':'bars');},[initial]);
  let form:RecordValue|null=null;try{form=JSON.parse(editor);if(!form||Array.isArray(form)||typeof form!=='object')form=null;}catch{}
  async function openResult(event:{body:RecordValue}){const id=event.body.artifact_id,kind=event.body.artifact_kind;if(typeof id!=='string'||typeof kind!=='string')return;try{setActive(await api<Artifact>(`/artifacts/${kind}/${id}`));setError('');}catch(e){setError((e as Error).message);}}
  async function connect(){try{setError('');const c=await api<Catalog>('/catalog');setCatalog(c);setEditor(v=>v==='{}'&&action==='save-hypothesis'?JSON.stringify(Object.values(c.templates)[0],null,2):v);setBar(v=>Object.keys(v).length?v:c.bar_defaults);setMm(v=>Object.keys(v).length?v:c.mm_defaults);const list=await api<{items:Summary[];total:number}>(`/artifacts/lab_dataset?offset=${datasetOffset}`);setDatasets(list.items);setDatasetTotal(list.total);}catch(e){setError((e as Error).message);}}
  useEffect(()=>{void connect();},[datasetOffset]);
  useEffect(()=>{let live=true;api<{items:Summary[];total:number}>(`/artifacts/${kind}?offset=${offset}`).then(r=>{if(live){setItems(r.items);setTotal(r.total);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[kind,offset,notice]);
  const status=job?.events.at(-1)?.action;
  useEffect(()=>{
    if(!job||!['queued','running','progress','cancel_requested'].includes(status||''))return;
    let stopped=false;let timer:ReturnType<typeof setTimeout>;
    const poll=async()=>{try{if(!document.hidden){const next=await api<Artifact>(`/artifacts/job/${job.id}`);if(stopped)return;setJob(next);const last=next.events.at(-1);if(last?.action==='completed'){setNotice('Computation completed. Saved result opened below.');void openResult(last);void connect();}else if(last?.action==='failed')setError(String(last.body.reason));}}catch(e){if(!stopped)setError((e as Error).message);}if(!stopped)timer=setTimeout(poll,1500);};
    timer=setTimeout(poll,800);return()=>{stopped=true;clearTimeout(timer);};
  },[job?.id,status]);
  async function execute(name:string,payload:unknown){setBusy(true);setError('');try{const result=await api<{id?:string;kind?:string;[key:string]:unknown}>('/actions/'+name,payload);if(result.id&&result.kind){const saved=await api<Artifact>(`/artifacts/${result.kind}/${result.id}`);setNotice(`Saved ${title(result.kind)} · ${result.id}`);if(result.kind==='job'){setJob(saved);const last=saved.events.at(-1);if(last?.action==='completed'){await openResult(last);setNotice('Computation completed. Saved result opened below.');}else if(last?.action==='failed')setError(String(last.body.reason));}else setActive(saved);}else setNotice(JSON.stringify(result,null,2));void connect();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function selectDataset(id:string){setDataset(id);setAck(false);try{const result=await api<Artifact>(`/artifacts/lab_dataset/${id}`);setActive(result);const request=result.artifact.request as {start:string;end:string};const first=new Date(request.start+'T00:00:00Z'),last=new Date(request.end+'T00:00:00Z'),middle=new Date((first.getTime()+last.getTime())/2);middle.setUTCHours(0,0,0,0);const b=new Date(middle);b.setUTCDate(b.getUTCDate()+1);setDates({a_start:request.start,a_end:middle.toISOString().slice(0,10),b_start:b.toISOString().slice(0,10),b_end:request.end});}catch(e){setError((e as Error).message);}}
  return <div className="flagship-workspace"><div className="flagship-toolbar"><h1>{initial}</h1><Button variant="outline" onClick={()=>void connect()}><RefreshCw size={16}/>Reconnect</Button></div>
    {error&&<p role="alert" className="flagship-warning">{error}</p>}{notice&&<details open><summary>Latest activity</summary><pre className="flagship-json">{notice}</pre></details>}
    {job&&<div className="flagship-toolbar"><span>{String(job.artifact.label)} · {status}</span>{status==='completed'&&Boolean(job.events.at(-1)?.body.artifact_kind)&&<Button variant="outline" onClick={()=>void openResult(job.events.at(-1)!)}>Open saved result</Button>}{['queued','running','progress'].includes(status||'')&&<Button variant="outline" onClick={()=>void execute('cancel',{id:job.id})}><Square size={14}/>Request cancellation</Button>}<small>Running bar and market-making calculations finish their current run; daily research and downloads support cooperative cancellation.</small></div>}
    {!catalog?<p>Starting the research engine…</p>:<Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="bars">Day & swing</TabsTrigger><TabsTrigger value="mm">Market making</TabsTrigger><TabsTrigger value="advanced">Advanced research</TabsTrigger><TabsTrigger value="library">Artifact library</TabsTrigger></TabsList>
      <TabsContent value="bars"><section className="flagship-panel"><h2>Historical market data</h2><div className="flagship-fields"><label>Source<Select value={source} onChange={e=>{setSource(e.target.value);if(e.target.value==='massive')setIntervalValue('1d');}}><Option value="yahoo">Yahoo Finance · real adjusted history</Option><Option value="massive">Massive · US daily</Option><Option value="synthetic">Synthetic scenario</Option></Select></label><label>Symbol<Input value={symbol} onChange={e=>setSymbol(e.target.value)} disabled={source==='synthetic'}/></label><label>Bar interval<Select value={interval} onChange={e=>setIntervalValue(e.target.value)}>{(source==='massive'?['1d']:['1d','1m','5m','15m']).map(i=><Option key={i}>{i}</Option>)}</Select></label><label>Start<Input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End · inclusive<Input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div>
      {source==='synthetic'?<><p className="flagship-warning">Artificial market history; weekdays and modeled India sessions without verified holidays.</p><div className="flagship-fields">{[['Seed',seed,setSeed],['Daily volatility',vol,setVol],['Daily drift',drift,setDrift]].map(([label,value,change])=><label key={String(label)}>{String(label)}<Input type="number" step="any" value={Number(value)} onChange={e=>(change as (v:number)=>void)(Number(e.target.value))}/></label>)}</div></>:<p>{source==='massive'?'Massive supports US daily history within the last two years and requires a key in Connections. Split-adjusted prices exclude cash dividends.':'Yahoo uses adjusted prices and approximate volume participation. Intraday coverage is limited; provider failures remain errors.'}</p>}
      <Button disabled={busy||!start||!end} onClick={()=>void execute('load-bars',{source,symbol,interval,start,end,seed,volatility:vol,drift})}>{source==='synthetic'?'Generate scenario':'Download history'}</Button></section>
      <section className="flagship-panel"><h2>Compare two periods</h2><label>Saved dataset<Select value={dataset} onChange={e=>void selectDataset(e.target.value)}><Option value="">Select historical data…</Option>{dataset&&!datasets.some(d=>d.id===dataset)&&<Option value={dataset}>{dataset}</Option>}{datasets.map(d=><Option key={d.id} value={d.id}>{d.name} · {d.id.slice(0,8)}</Option>)}</Select></label>{datasetTotal>50&&<div className="flagship-toolbar"><Button variant="outline" disabled={!datasetOffset} onClick={()=>setDatasetOffset(Math.max(0,datasetOffset-50))}>Previous datasets</Button><span>{datasetTotal} saved datasets · page {datasetOffset/50+1}</span><Button variant="outline" disabled={datasetOffset+50>=datasetTotal} onClick={()=>setDatasetOffset(datasetOffset+50)}>Next datasets</Button></div>}<Fields schema={catalog.bar} value={bar} change={setBar}/><div className="flagship-fields">{Object.entries(dates).map(([key,value])=><label key={key}>{title(key)}<Input type="date" value={value} onChange={e=>setDates({...dates,[key]:e.target.value})}/></label>)}</div><p>Both periods reset cash and warm-up. Signals execute at the next observed open. This comparison is exploratory, not untouched holdout testing.</p><label className="flagship-check"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>I reviewed the selected data’s source, actual coverage and execution assumptions.</label><Button disabled={busy||!dataset||!ack} onClick={()=>void execute('compare',{dataset_id:dataset,config:bar,...dates,acknowledge:ack})}><Play size={16}/>Compare periods</Button></section></TabsContent>
      <TabsContent value="mm"><section className="flagship-panel"><h2>Synthetic two-venue market</h2><p className="flagship-warning">Market making and latency arbitrage simulation. Yahoo and Massive OHLCV bars are not empirical order-book data. Choose either provider under Day & swing or Advanced research for bar-based models.</p><details><summary>Market and execution assumptions</summary>{catalog.mm_limitations.map(note=><p key={note}>{note}</p>)}</details><Fields schema={catalog.mm} value={mm} change={setMm}/><label className="flagship-check"><input type="checkbox" checked={mmAck} onChange={e=>setMmAck(e.target.checked)}/>I understand these are synthetic results and paired arbitrage fills assume atomic hedging.</label><Button disabled={busy||!mmAck} onClick={()=>void execute('market-making',mm)}><Play size={16}/>Run scenario and latency sensitivity</Button></section></TabsContent>
      <TabsContent value="advanced"><section className="flagship-panel"><h2>Quantitative research workbench</h2><Select aria-label="Research action" value={action} onChange={e=>{actionDrafts.current[action]=editor;setAction(e.target.value);setEditor(actionDrafts.current[e.target.value]||JSON.stringify(actions[e.target.value].payload,null,2));}}>{Object.entries(actions).map(([key,a])=><Option key={key} value={key}>{a.label}</Option>)}</Select><p>{actions[action].note}</p>{['guidance','save-hypothesis'].includes(action)&&<Select aria-label="Hypothesis template" onChange={e=>{const template=catalog.templates[e.target.value];if(template)setEditor(JSON.stringify(template,null,2));}}><Option value="">Choose formulation template…</Option>{Object.keys(catalog.templates).map(k=><Option key={k}>{k}</Option>)}</Select>}
      {action==='history-import'&&<label>Price matrix CSV<Input type="file" accept=".csv" onChange={async e=>{const file=e.target.files?.[0];if(file)try{setEditor(JSON.stringify({...JSON.parse(editor),csv:await file.text()},null,2));}catch{setError('Correct the JSON before attaching a CSV.');}}}/></label>}
      {action==='import-csv'&&<div className="flagship-fields"><label>Historical CSV<Input type="file" accept=".csv" onChange={async e=>{const file=e.target.files?.[0];if(file)try{setEditor(JSON.stringify({...JSON.parse(editor),csv:await file.text()},null,2));}catch{setError('Correct the JSON before attaching a CSV.');}}}/></label><label>Source manifest<Input type="file" accept=".json" onChange={async e=>{const file=e.target.files?.[0];if(file)try{setEditor(JSON.stringify({...JSON.parse(editor),metadata:JSON.parse(await file.text())},null,2));}catch{setError('Invalid source manifest JSON.');}}}/></label></div>}
      {form&&<GuidedInputs action={action} value={form} change={v=>setEditor(JSON.stringify(v,null,2))} schema={action==='freeze-strategy'?catalog.strategy:['save-hypothesis','guidance'].includes(action)?catalog.hypothesis:catalog.quant?.[action]?.schema}/>}<details><summary>Advanced specification · JSON</summary><textarea className="research-textarea" aria-label="Research specification JSON" rows={18} value={editor} onChange={e=>setEditor(e.target.value)}/></details><Button disabled={busy} onClick={()=>{try{void execute(action,JSON.parse(editor));}catch{setError('Correct the JSON before running this action.');}}}>{actions[action].label}</Button><details><summary>Full strategy and calendar contracts</summary><Json value={{strategy:catalog.strategy,calendar:catalog.calendar}}/></details></section>
      <section className="flagship-panel"><h2>Angel One historical-data session</h2><p>Use the local credential setup to retain Evidence’s historical-data access. Authentication values stay in backend memory. The Q account connections remain available under Connections.</p><p>From the apps/engine directory:</p><code>./.venv/Scripts/python.exe -m evidence.cli credentials</code><div className="flagship-toolbar"><Input aria-label="Current six-digit TOTP" type="password" autoComplete="off" value={totp} onChange={e=>setTotp(e.target.value)} placeholder="Current TOTP, or stored seed"/><Button disabled={busy} onClick={()=>{const value=totp;setTotp('');void execute('angel-connect',{totp:value});}}>Connect history</Button><Button variant="outline" onClick={()=>void execute('angel-disconnect',{})}>Disconnect</Button></div></section></TabsContent>
      <TabsContent value="library"><section className="flagship-panel"><h2>Saved artifacts and audit history</h2><details><summary>Shared reports from the former regime project</summary><p>These files were shared across old runs and may have been overwritten there. Their migration-time hashes are retained; they are not attributed to individual experiments.</p><a className="button secondary" href={`${base}/legacy-reports/export`}>Export shared legacy reports</a></details><div className="flagship-toolbar"><Select aria-label="Artifact type" value={kind} onChange={e=>{setKind(e.target.value);setOffset(0);}}>{catalog.kinds.map(k=><Option key={k} value={k}>{title(k)}</Option>)}</Select><Button variant="outline" onClick={()=>setNotice('Library refreshed at '+new Date().toLocaleTimeString())}><RefreshCw size={16}/>Refresh</Button></div>{items.map(item=><button className="flagship-artifact" key={item.id} onClick={()=>{setError('');void api<Artifact>(`/artifacts/${kind}/${item.id}`).then(record=>{setActive(record);if(record.kind==='job')setJob(record);}).catch(e=>setError(e.message));}}><strong>{item.name}</strong><span>{item.created} · {item.id.slice(0,12)}</span></button>)}{!items.length&&<p>No saved {title(kind).toLowerCase()} yet.</p>}<div className="flagship-toolbar"><span>{total} artifacts</span><Button variant="outline" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</Button><Button variant="outline" disabled={offset+50>=total} onClick={()=>setOffset(offset+50)}>Next</Button></div></section></TabsContent>
    </Tabs>}{active&&<section className="flagship-panel">{active.kind==='hypothesis'&&<Button variant="outline" onClick={()=>{setAction('save-hypothesis');setEditor(JSON.stringify({...active.artifact,version:Number(active.artifact.version||1)+1,created_at:new Date().toISOString()},null,2));setTab('advanced');}}>Edit as new hypothesis version</Button>}<Result key={active.id} record={active}/></section>}
  </div>;
}
