"use client";
import {useState} from 'react';
import {Code2,Globe2,Activity,RefreshCw,ShieldCheck,ExternalLink,LogIn} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
import {integrationRequest,type IntegrationStatus} from '@/hooks/use-integrations';
import MassiveConnection from './massive-connection';
export default function ConnectionsPanel({status,refresh,newConversation}:{status:IntegrationStatus;refresh:()=>Promise<IntegrationStatus>;newConversation:()=>Promise<void>}){
  const [angelOpen,setAngelOpen]=useState(false),[busy,setBusy]=useState(false),[snapshot,setSnapshot]=useState<Record<string,unknown>|null>(null),[loginUrl,setLoginUrl]=useState('');
  const [fields,setFields]=useState({apiKey:'',clientCode:'',pin:'',totp:'',publicIp:''});
  const action=async(fn:()=>Promise<unknown>)=>{try{setBusy(true);await fn();await refresh();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}};
  const signInAngel=async()=>{
    const credentials={...fields};setFields({apiKey:'',clientCode:'',pin:'',totp:'',publicIp:''});
    await action(async()=>{const result=await integrationRequest('/angel/login',credentials);if(result.connected!==true)throw new Error('Angel One could not verify this login. Check your credentials and try again.');setAngelOpen(false);toast.success('Angel One connected with read-only account access.');});
  };
  return <>
    <div className="integration-heading"><p><ShieldCheck size={15}/>Broker account access is read-only. Paper order simulation stays separate.</p><button className="button secondary" disabled={busy} onClick={()=>action(refresh)}><RefreshCw size={14}/>Refresh status</button></div>
    {!status.gateway&&<div className="integration-alert">Local gateway unavailable. Start Q with <code>start-q21.ps1</code> to enable these connections.</div>}
    <div className="connection-grid">
      <MassiveConnection connection={status.massive} gateway={status.gateway} refresh={refresh}/>
      <article className="connection-card"><Code2 size={25}/><span className={`badge ${status.codex.connected?'demo':'neutral'}`}>{status.codex.connected?'CONNECTED':'SIGN-IN REQUIRED'}</span><h2>Codex</h2><p>{status.codex.connected?'Your signed-in ChatGPT account · Strategy development':'Connect your Codex account through the official browser login.'}</p><div className="connection-detail">Custom code and parameters · Isolated projects · Saved versions</div><div className="connection-actions"><button className="button secondary" disabled={busy||!status.gateway} onClick={()=>action(async()=>{if(status.codex.connected){await newConversation();toast.success('New Codex conversation started.');}else{const r=await integrationRequest('/codex/login',{});if(typeof r.authUrl==='string')setLoginUrl(r.authUrl);}})}>{status.codex.connected?'New conversation':'Sign in to Codex'}<LogIn size={14}/></button></div>{loginUrl&&<a className="connection-link" href={loginUrl} target="_blank" rel="noreferrer">Complete Codex sign-in <ExternalLink size={13}/></a>}</article>
      <article className="connection-card"><Activity size={25}/><span className={`badge ${status.angel.connected?'demo':'neutral'}`}>{status.angel.connected?'CONNECTED':'SIGN-IN REQUIRED'}</span><h2>Angel One</h2><p>India · SmartAPI account and holdings</p><div className="connection-detail">{status.angel.connected?`Account ${status.angel.account} · Read-only`:'Client code, SmartAPI key, PIN, and current TOTP required'}</div><div className="connection-actions"><button className="button primary" disabled={busy||!status.gateway} onClick={()=>setAngelOpen(true)}>{status.angel.connected?'Reconnect':'Sign in securely'}</button>{status.angel.connected&&<><button className="button secondary" disabled={busy} onClick={()=>action(async()=>setSnapshot(await integrationRequest('/angel/account')))}>View account</button><button className="text-button" disabled={busy} onClick={()=>action(async()=>{await integrationRequest('/angel/disconnect',{});toast.success('Angel One disconnected from Q.');})}>Disconnect</button></>}</div></article>
      <article className="connection-card"><Globe2 size={25}/><span className={`badge ${status.ibkr.connected?'demo':'neutral'}`}>{status.ibkr.connected?'CONNECTED':status.ibkr.gatewayAvailable?'LOGIN REQUIRED':'GATEWAY OFFLINE'}</span><h2>Interactive Brokers</h2><p>Client Portal Gateway · Account and positions</p><div className="connection-detail">{status.ibkr.connected?'Authenticated gateway session · Read-only':status.ibkr.gatewayAvailable?'Complete IBKR authentication in its own login window.':'Start the installed gateway with start-ibkr.ps1, then sign in.'}</div><div className="connection-actions"><a className="button secondary" href={status.ibkr.loginUrl||'https://localhost:5000'} target="_blank" rel="noreferrer">Open IBKR login <ExternalLink size={13}/></a>{status.ibkr.connected&&<button className="button secondary" disabled={busy} onClick={()=>action(async()=>setSnapshot(await integrationRequest('/ibkr/account')))}>View account</button>}</div><p className="connection-help">IBKR may show a certificate warning for its local gateway. Complete your own account login and two-factor authentication, then refresh status here.</p></article>
    </div>
    <Dialog open={angelOpen} onOpenChange={open=>{setAngelOpen(open);if(!open)setFields({apiKey:'',clientCode:'',pin:'',totp:'',publicIp:''});}}><DialogContent><DialogHeader><DialogTitle>Connect Angel One</DialogTitle><DialogDescription>Credentials go only to your local Q backend and Angel One. PIN and TOTP are discarded after login; the session remains in backend memory until restart or disconnect.</DialogDescription></DialogHeader><form className="order-form" onSubmit={e=>{e.preventDefault();void signInAngel();}}>{[{key:'apiKey',label:'SmartAPI key',type:'password'},{key:'clientCode',label:'Angel One client code',type:'text'},{key:'pin',label:'Trading PIN',type:'password'},{key:'totp',label:'Current authenticator code (TOTP)',type:'password'}].map(({key,label,type})=><label key={key}>{label}<input type={type} required autoComplete="off" value={fields[key as keyof typeof fields]} inputMode={key==='totp'||key==='pin'?'numeric':undefined} maxLength={key==='totp'?6:200} onChange={e=>setFields({...fields,[key]:e.target.value})}/></label>)}<details><summary>Advanced: public IP</summary><label>Public IP (optional)<input value={fields.publicIp} onChange={e=>setFields({...fields,publicIp:e.target.value})} placeholder="Auto-detect using ipify"/></label></details><button className="button primary full" disabled={busy}>{busy?'Verifying account…':'Connect with read-only access'}</button></form></DialogContent></Dialog>
    <Dialog open={!!snapshot} onOpenChange={open=>{if(!open)setSnapshot(null);}}><DialogContent className="broker-snapshot"><DialogHeader><DialogTitle>{String(snapshot?.source||'Broker')} account snapshot</DialogTitle><DialogDescription>Retrieved from your broker. Account identifiers are masked; no order actions are available.</DialogDescription></DialogHeader><pre className="code-view">{JSON.stringify(snapshot,null,2)}</pre></DialogContent></Dialog>
  </>;
}
