"use client";
import {useState} from 'react';
import {Database,Upload,RefreshCw} from 'lucide-react';
import {toast} from 'sonner';
import type {Catalogue,Dataset,Quote} from '@/lib/market-types';
import {integrationRequest} from '@/hooks/use-integrations';
export default function DataPanel({catalogue,quotes,accept,refresh}:{catalogue:Catalogue;quotes:Quote[];accept:(d:Dataset)=>void;refresh:()=>void}){
  const [symbol,setSymbol]=useState('NVDA'),[source,setSource]=useState(''),[file,setFile]=useState<File|null>(null),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false);
  async function importFile(){if(!file)return;setBusy(true);try{if(file.size>4000000)throw new Error('Choose a CSV smaller than 4 MB.');const result=await integrationRequest('/market/import',{symbol,source,csv:await file.text(),unadjustedConfirmed:confirmed}) as unknown as Dataset;accept(result);toast.success(`${result.bars.length} real historical bars imported for ${symbol}.`);}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  return <><div className="panel"><div className="panel-heading"><div><h2>Market data sources</h2><p>Official instrument directories · Massive US daily history · Your CSV datasets</p></div><button className="button secondary" onClick={refresh}><RefreshCw size={14}/>Refresh directories</button></div><div className="data-pairs">{catalogue.sources.map(s=><div key={s.name}><span>{s.name}</span><strong>{s.count.toLocaleString()} securities · {s.status}<small className="data-date">{s.asOf?new Date(s.asOf).toLocaleString():'Not downloaded'}</small></strong></div>)}</div><p className="panel-note">Select a source above for terminal history and backtests. Yahoo covers supported US/NSE symbols. Massive requires an API key and supports US daily history. Synthetic is an explicit seeded scenario with fixed dates, never a fallback. CSV imports retain their original provenance.</p></div><div className="panel"><div className="panel-heading"><div><h2>Import historical CSV</h2><p>Save an immutable dataset and use it for the next backtest.</p></div><Upload size={18}/></div><div className="order-form"><label>Catalogue symbol<input value={symbol} onChange={e=>setSymbol(e.target.value.trim().toUpperCase())} placeholder="NVDA or RELIANCE.NS"/></label><label>Actual data provider / source<input value={source} onChange={e=>setSource(e.target.value)} maxLength={150} placeholder="Provider name and export reference"/></label><label>CSV file<input type="file" accept=".csv,text/csv" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><p className="panel-note">Required columns: date, open, high, low, close, volume. Dates: YYYY-MM-DD. Optional: split_ratio (new shares / old shares on effective date), dividend (cash per share on ex-date). Use unadjusted historical prices. No missing values, duplicate dates, or current-day bars.</p><label className="csv-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>This file contains real, unadjusted historical data, with corporate actions included where applicable.</label><button className="button primary" disabled={busy||!file||!confirmed||!source.trim()} onClick={importFile}>{busy?'Validating…':'Validate & import'}</button></div></div><section className="panel"><div className="panel-heading"><div><h2>Loaded dataset snapshots</h2><p>Stored on this computer; source versions remain reproducible.</p></div><Database size={18}/></div>{quotes.map(q=><div className="dataset-row" key={q.symbol}><strong>{q.symbol}</strong><span>{q.dataset.source}</span><span>{q.bars.length} bars · through {q.dataset.asOf}</span><small>{q.dataset.id.slice(0,12)} · {q.dataset.stale?'Refresh failed; cached history':'Historical data'}</small></div>)}{!quotes.length&&<p className="panel-note">No history loaded. Open an instrument in Markets or import a CSV.</p>}</section></>;
}
