"use client";
import {useMemo,useState} from 'react';
import {Search,ArrowRight,RefreshCw} from 'lucide-react';
import type {Catalogue,Quote} from '@/lib/market-types';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
export default function MarketBrowser({catalogue,quotes,research,refresh,busy,error}:{catalogue:Catalogue;quotes:Quote[];research:(symbol:string)=>void;refresh:()=>void;busy:boolean;error?:string}){
  const [query,setQuery]=useState(''),[exchange,setExchange]=useState('All exchanges'),[type,setType]=useState('All types'),[offset,setOffset]=useState(0);
  const matches=useMemo(()=>catalogue.instruments.filter(i=>(exchange==='All exchanges'||i.exchange===exchange)&&(type==='All types'||i.type===type)&&`${i.symbol} ${i.name} ${i.isin||''}`.toLowerCase().includes(query.toLowerCase())),[catalogue,exchange,type,query]);
  return <section className="panel market-browser"><div className="panel-heading"><div><h2>Nasdaq & NSE</h2><p>{catalogue.instruments.length.toLocaleString()} listed securities · Search the catalogue, then open daily history</p></div><button className="button secondary" disabled={busy} onClick={refresh}><RefreshCw size={14}/>Refresh catalogue</button></div><div className="filter-toolbar catalogue-filters"><div className="search-field"><Search size={16}/><input aria-label="Search full exchange catalogue" placeholder="Symbol, company or ISIN" value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}}/></div>{[[exchange,setExchange,['All exchanges','NASDAQ','NSE'],'Exchange'],[type,setType,['All types','Listed security','Equity','ETF','SME'],'Security type']].map(([value,setter,options,label])=><Select key={label as string} value={value as string} onValueChange={v=>{(setter as (s:string)=>void)(v);setOffset(0);}}><SelectTrigger aria-label={label as string}><SelectValue/></SelectTrigger><SelectContent>{(options as string[]).map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select>)}</div>{error&&<p className="data-error">{error}</p>}{catalogue.sources.filter(s=>s.status==='unavailable'||s.error).map(s=><p className="data-error" key={s.name}>{s.name}: {s.error}</p>)}<Table><TableHeader><TableRow>{['SYMBOL','COMPANY','EXCHANGE','TYPE','LAST LOADED CLOSE',''].map((h,i)=><TableHead key={i}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{matches.slice(offset,offset+50).map(i=>{const q=quotes.find(q=>q.symbol===i.symbol);return <TableRow key={i.symbol}><TableCell><button onClick={()=>research(i.symbol)}>{i.symbol}</button></TableCell><TableCell className="company-cell">{i.name}</TableCell><TableCell>{i.exchange}</TableCell><TableCell>{i.type}</TableCell><TableCell>{q?<>{q.price.toLocaleString(undefined,{maximumFractionDigits:2})} {i.currency}<small className="data-date">{q.dataset.asOf} · {q.dataset.source}</small></>:'Not loaded'}</TableCell><TableCell><button className="text-button" onClick={()=>research(i.symbol)}>Research<ArrowRight size={14}/></button></TableCell></TableRow>;})}</TableBody></Table>{!matches.length&&<p className="panel-note">{busy?'Loading official exchange directories…':'No matching instruments. Refresh the catalogue or change your filters.'}</p>}<div className="catalogue-pagination"><span>{matches.length?offset+1:0}–{Math.min(offset+50,matches.length)} of {matches.length.toLocaleString()}</span><button className="button secondary" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</button><button className="button secondary" disabled={offset+50>=matches.length} onClick={()=>setOffset(offset+50)}>Next</button></div><p className="panel-note">Current listings; historical constituents and complete delisted coverage are not included. Daily history availability varies by instrument.</p></section>;
}
