"use client";
import {useState} from 'react';
import {Database,ExternalLink} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
import {integrationRequest,type Connection} from '@/hooks/use-integrations';
export default function MassiveConnection({connection,gateway,refresh}:{connection?:Connection;gateway:boolean;refresh:()=>Promise<unknown>}){
  const [open,setOpen]=useState(false),[key,setKey]=useState(''),[busy,setBusy]=useState(false);
  async function connect(){const apiKey=key;setKey('');setBusy(true);try{await integrationRequest('/massive/connect',{apiKey});await refresh();setOpen(false);window.dispatchEvent(new Event('q21-market-connected'));toast.success('Massive key verified. Loading the selected US history.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  async function disconnect(){setBusy(true);try{await integrationRequest('/massive/disconnect',{});await refresh();toast.success('Massive disconnected. Saved historical datasets remain available.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  return <><article className="connection-card"><Database size={25}/><span className={`badge ${connection?.connected?'demo':'neutral'}`}>{connection?.connected?'KEY VERIFIED':'API KEY REQUIRED'}</span><h2>Massive</h2><p>Nasdaq / US equities · Real historical daily bars</p><div className="connection-detail">Two-year request window · Five API calls/minute · Splits and dividends included</div><div className="connection-actions"><button className="button primary" disabled={!gateway||busy} onClick={()=>setOpen(true)}>{connection?.connected?'Replace API key':'Connect Massive'}</button>{connection?.connected&&<button className="text-button" disabled={busy} onClick={()=>void disconnect()}>Disconnect</button>}<a className="text-button" href="https://massive.com/dashboard" target="_blank" rel="noreferrer">Get API key<ExternalLink size={13}/></a></div><p className="connection-help">Stocks Basic can be used for end-of-day research. Data access depends on your plan. Massive does not cover NSE; import NSE history under Data.</p>{connection?.message&&<p className="data-error">{connection.message}</p>}</article><Dialog open={open} onOpenChange={v=>{setOpen(v);if(!v)setKey('');}}><DialogContent><DialogHeader><DialogTitle>Connect Massive</DialogTitle><DialogDescription>Enter the API key from your Massive dashboard. It is sent only to the local Q backend and Massive, and kept in backend memory until disconnect or restart. It is never saved in browser storage or sent to Codex.</DialogDescription></DialogHeader><form className="order-form" onSubmit={e=>{e.preventDefault();void connect();}}><label>Massive API key<input type="password" autoComplete="off" value={key} required maxLength={200} onChange={e=>setKey(e.target.value)}/></label><button className="button primary" disabled={busy||!key.trim()}>{busy?'Verifying key…':'Verify & connect'}</button><p className="panel-note">Verification uses one reference-data request. Loading a history requires bars, splits and dividends, so it can take about 40 seconds on the free plan.</p></form></DialogContent></Dialog></>;
}
