"use client";
import {useEffect,useState} from 'react';
import {Code2,Plus,RefreshCw,ArrowDownToLine,Database} from 'lucide-react';
import {toast} from 'sonner';
import {integrationRequest,type useIntegrations} from '@/hooks/use-integrations';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';

export default function StrategyDevelopment({integration,symbol,source,discuss}:{integration:ReturnType<typeof useIntegrations>;symbol:string;source:string;discuss:(text:string)=>void}){
  const {project,projects,busy}=integration;
  const [name,setName]=useState(''),[file,setFile]=useState(''),[content,setContent]=useState(''),[parameters,setParameters]=useState('{}'),[working,setWorking]=useState(false);
  useEffect(()=>{let cancelled=false;setFile('');setContent('');setParameters('{}');if(project)void integrationRequest(`/codex/project/file?id=${project.id}&path=parameters.json`).then(r=>{if(!cancelled)setParameters(String(r.text));}).catch(e=>{if(!cancelled)toast.error(e.message);});return()=>{cancelled=true;};},[project?.id,project?.updatedAt]);
  const action=async(fn:()=>Promise<unknown>)=>{setWorking(true);try{await fn();}catch(e){toast.error((e as Error).message);}finally{setWorking(false);}};
  const view=async(name:string)=>{if(!project)return;const result=await integrationRequest(`/codex/project/file?id=${project.id}&path=${encodeURIComponent(name)}`);setFile(name);setContent(String(result.text));};
  const download=async(version:string)=>{if(!project)return;const snapshot=await integrationRequest(`/codex/project/snapshot?id=${project.id}&version=${version}`);const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`${project.name}-${version.slice(0,8)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <section className="panel development-workspace"><div className="panel-heading"><div><h2><Code2 size={17}/> Custom strategy development</h2><p>Discuss an idea with Codex, build the code, and review saved versions. Define your own rules and parameters.</p></div><button className="button secondary" disabled={working||busy} onClick={()=>action(integration.refreshProjects)}><RefreshCw size={14}/>Refresh</button></div>
    <div className="development-controls"><Select value={project?.id||''} onValueChange={id=>void action(()=>integration.chooseProject(id))} disabled={busy||working}><SelectTrigger aria-label="Development project"><SelectValue placeholder="Choose a strategy project"/></SelectTrigger><SelectContent>{projects.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select><form onSubmit={e=>{e.preventDefault();void action(async()=>{await integration.createProject(name.trim()||'Custom strategy');setName('');});}}><input aria-label="New strategy project name" placeholder="Name a new strategy…" value={name} maxLength={100} onChange={e=>setName(e.target.value)}/><button className="button primary" disabled={busy||working}><Plus size={14}/>New project</button></form></div>
    {project?<><div className="development-actions"><button className="button primary" disabled={busy||working} onClick={()=>discuss('Develop this strategy with me. Read the project specification and parameters, then help me define and implement the rules we discuss. Do not constrain the design to Q’s built-in strategy templates.')}><Code2 size={14}/>Develop with Codex</button><button className="button secondary" disabled={busy||working} onClick={()=>action(async()=>{await integrationRequest('/codex/project/dataset',{id:project.id,symbol,source});await integration.refreshProjects();toast.success(`${symbol} history attached with its source and dataset version.`);})}><Database size={14}/>Attach {symbol} · {source}</button><span className="muted">Research project · No live execution</span></div>
    <div className="development-grid"><div><h3>Custom parameters</h3><p className="muted">Any named JSON settings your implementation needs. Code defines their meaning and validation.</p><textarea className="development-code" aria-label="Custom strategy parameters JSON" spellCheck={false} value={parameters} disabled={busy||working} onChange={e=>setParameters(e.target.value)}/><button className="button secondary" disabled={busy||working} onClick={()=>action(async()=>{await integrationRequest('/codex/project/parameters',{id:project.id,parameters:JSON.parse(parameters)});await integration.refreshProjects();toast.success('Parameters saved as a new version.');})}>Save parameters</button></div>
    <div><h3>Implementation & research files</h3><div className="development-files">{project.files?.map(f=><button key={f.path} className={file===f.path?'active':''} disabled={working||busy} onClick={()=>action(()=>view(f.path))}>{f.path}<small>{Math.ceil(f.bytes/1024)} KB</small></button>)}</div><p className="muted">Ask Codex to implement, revise, test, or backtest these files using attached data. The template backtester below is a separate workflow.</p></div></div>
    {file&&<div className="development-preview"><h3>{file}</h3><pre className="code-view">{content}</pre></div>}
    <div className="development-versions"><h3>Saved versions</h3>{project.snapshots.length?project.snapshots.slice().reverse().map(s=><button key={s.id} className="button secondary" onClick={()=>action(()=>download(s.id))} disabled={working}><ArrowDownToLine size={13}/>{s.label} · {s.id.slice(0,8)}</button>):<p className="muted">Versions are saved before and after Codex work and parameter changes.</p>}</div></>:<div className="development-empty"><p>Create a project or send Codex your idea to start. Custom strategy code can define new indicators, entry and exit rules, sizing, and parameters.</p></div>}
  </section>;
}
